MongoShop/Areas/AppManage/Controllers/ProductManageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoShop.Data;
using MongoShop.Models.Entities;
using MongoShop.MongoDb;

namespace MongoShop.Areas.AppManage.Controllers
{
    [Authorize(Roles = RoleName.Administrator)]
    [Route("[controller]/[action]")]
    [Area("AppManage")]
    public class ProductManageController : Controller
    {
        
        private readonly MongoRepository<Product> _productRepository;

        public ProductManageController(MongoRepository<Product> productRepository)
        {
            _productRepository = productRepository;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllAsync();
            return View(products);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.CreateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.UpdateAsync(id, product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _productRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MongoShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MongoShop.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MongoShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MongoShop</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
  
    <link rel="stylesheet" href="~/css/site.css" />
    @(await RenderSectionAsync("Head", required: false))
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    MongoShop
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">
                    Sản phẩm
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Giỏ hàng
                </a>
              
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <partial name="_MenuManagePartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MongoShop - Cơ sở dữ liệu nâng cao
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  
    @RenderSection("Scripts", required: false)
</body>
</html>

MongoShop/Views/Shared/_MenuManagePartial.cshtml
@using Microsoft.AspNetCore.Authorization;
@inject IAuthorizationService authorizationServer;


@{
    var result = await authorizationServer.AuthorizeAsync(this.User, "viewManageMenu");
}


@if (result.Succeeded)
{
   

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <strong>Quản trị</strong>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li> <a class="dropdown-item" asp-action="Index" asp-controller="ProductManage" asp-area="AppManage">Quản lý sản phẩm</a></li>
        </ul>
    </div>

}